# number of pictures to display in one row
columns: 3

# how many ticks are shown (if 0 --> show full trajectory)
show_n_ticks: 1000
ymin: 0.5
ymax: 4.0
shade_passive_alpha: 0.2
shade_active_alpha: 0.6
# colors of the shade (cycled through)
shade_colors:
  - "#1f77b4"
  - "#ff7f0e"