# tick interval for simulation (default=1000)
tick_interval: 2000
seed: 6
# maximal value for truncating normal distribution (default=0.2)
noise_max: 0.2
# variance of normal distribution (default=0.01)
noise_variance: 0.01

start_time: "14:00"
drinks:
  - name: "Cola Rum"
    points:
    - value: 2.5
      time: "14:00"
    - value: 2.5
      time: "23:50"
    - value: 2.0
      time: "00:00"
    - value: 2.0
      time: "00:30"
    - value: 2.5
      time: "00:40"
    - value: 2.5
      time: "03:00"
  - name: "Cappy Vodka"
    points:
    - value: 3.0
      time: "14:00"
    - value: 3.0
      time: "23:50"
    - value: 2.0
      time: "00:00"
    - value: 2.0
      time: "00:30"
    - value: 3.0
      time: "00:40"
    - value: 3.0
      time: "03:00"
  - name: "Wüstenwasser"
    points:
    - value: 2.5
      time: "14:00"
    - value: 2.5
      time: "23:50"
    - value: 2.0
      time: "00:00"
    - value: 2.0
      time: "00:30"
    - value: 2.5
      time: "00:40"
    - value: 2.5
      time: "03:00"
  - name: "Red Red"
    points:
    - value: 3.0
      time: "14:00"
    - value: 3.0
      time: "23:50"
    - value: 2.0
      time: "00:00"
    - value: 2.0
      time: "00:30"
    - value: 2.5
      time: "00:40"
    - value: 2.5
      time: "03:00"
  - name: "Vodka Bull"
    points:
    - value: 3.5
      time: "14:00"
    - value: 3.5
      time: "23:50"
    - value: 1.5
      time: "00:00"
    - value: 1.5
      time: "00:30"
    - value: 3.0
      time: "00:40"
    - value: 3.0
      time: "03:00"
  - name: "Gin Tonic"
    points:
    - value: 3.5
      time: "14:00"
    - value: 3.5
      time: "23:50"
    - value: 2.0
      time: "00:00"
    - value: 2.0
      time: "00:30"
    - value: 2.5
      time: "00:40"
    - value: 2.5
      time: "03:00"
  - name: "Bacardi Cola"
    points:
    - value: 3.0
      time: "14:00"
    - value: 3.0
      time: "23:50"
    - value: 2.0
      time: "00:00"
    - value: 2.0
      time: "00:30"
    - value: 2.5
      time: "00:40"
    - value: 2.5
      time: "03:00"
  - name: "Dreh & Drink"
    points:
    - value: 3.0
      time: "14:00"
    - value: 3.0
      time: "23:50"
    - value: 2.0
      time: "00:00"
    - value: 2.0
      time: "00:30"
    - value: 2.5
      time: "00:40"
    - value: 2.5
      time: "03:00"
